name: mlops-two-testing-pipeline
on: [push]

# Add permissions to fix the comment creation issue
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    # Remove container to avoid glibc compatibility issues
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This is important for DVC to access git history
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install DVC and dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc
      
      - name: 'Setup CML'
        uses: iterative/setup-cml@v1
      
      - name: 'Train and evaluate model'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run your DVC pipeline
          dvc repro
          
          # Generate metrics comparison
          dvc metrics diff --show-md main > report.md
          
          # Add figure to report
          echo -e "\n## ROC Graph for the model" >> report.md
          echo "![](./ROC.png)" >> report.md
          
          # Use updated CML command
          cml comment create report.md
