name: mlops-two-testing-pipeline
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install DVC and dependencies
        run: |
          pip install scikit-learn pandas numpy matplotlib seaborn
          pip install dvc gdown
      
      - name: 'Train and evaluate model'
        run: |
          # Run your DVC pipeline
          dvc repro
      
      - name: 'Create report'
        run: |
          # Create a basic report header
          echo "## Model Metrics" > report.md
          echo "" >> report.md
          echo "| Metric | Value |" >> report.md
          echo "| ------ | ----- |" >> report.md
          
          # Create a separate Python script to format metrics
          cat > format_metrics.py << 'EOF'
import json
with open('metrics.json', 'r') as f:
    metrics = json.load(f)
for key, value in metrics.items():
    formatted_key = key.replace('_', ' ').replace('-', ' ').title()
    print(f"| {formatted_key} | {value:.4f} |")
EOF
          
          # Run the Python script and append output to report
          python format_metrics.py >> report.md
          
          # Add ROC curve section
          echo "" >> report.md
          echo "## ROC Graph for the model" >> report.md
          echo "" >> report.md
          echo "ROC curve is available in the artifacts as ROC.png" >> report.md
      
      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            ROC.png
            metrics.json
            report.md
      
      # Use commit comment action with PAT
      - name: Create commit comment
        uses: peter-evans/commit-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          body-path: report.md
