name: mlops-two-testing-pipeline
on: [push]

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install DVC and dependencies
        run: |
          pip install scikit-learn pandas numpy matplotlib seaborn
          pip install dvc gdown
      
      - name: 'Train and evaluate model'
        run: |
          # Run your DVC pipeline
          dvc repro
          
          # Create metrics report from metrics.json
          echo "## Model Metrics" > report.md
          echo '```json' >> report.md
          cat metrics.json >> report.md
          echo '```' >> report.md
          
          # Add figure to report
          echo -e "\n## ROC Graph for the model" >> report.md
          echo "![ROC Curve](ROC.png)" >> report.md
      
      # Use GitHub's own action to upload artifacts (updated to v4)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            ROC.png
            metrics.json
            report.md
      
      # Use a different action for creating comments (updated to the latest version)
      - name: Create commit comment
        uses: peter-evans/commit-comment@v3
        with:
          body-path: report.md
