name: mlops-two-testing-pipeline
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install DVC and dependencies
        run: |
          pip install scikit-learn pandas numpy matplotlib seaborn
          pip install dvc gdown
      
      - name: Train model
        run: |
          dvc repro
      
      - name: Setup CML
        uses: iterative/setup-cml@v1
        
      - name: Generate CML report with metrics and ROC
        env:
          REPO_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          echo "" >> report.md
          echo "### Model Accuracy" >> report.md
          echo "" >> report.md
          python -c "import json; data = json.load(open('metrics.json')); print(f'- Dummy: {data[\"accuracy_dummy\"]:.4f}')" >> report.md
          python -c "import json; data = json.load(open('metrics.json')); print(f'- KNN: {data[\"accuracy_KNN\"]:.4f}')" >> report.md
          python -c "import json; data = json.load(open('metrics.json')); print(f'- Logistic Regression: {data[\"accuracy_logistic-regression\"]:.4f}')" >> report.md
          
          echo "" >> report.md
          echo "### AUC Values" >> report.md
          echo "" >> report.md
          python -c "import json; data = json.load(open('metrics.json')); print(f'- Dummy: {data[\"AUC_dummy\"]:.4f}')" >> report.md
          python -c "import json; data = json.load(open('metrics.json')); print(f'- KNN: {data[\"AUC_KNN\"]:.4f}')" >> report.md
          python -c "import json; data = json.load(open('metrics.json')); print(f'- Logistic Regression: {data[\"AUC_logistic-regression\"]:.4f}')" >> report.md
          
          echo "" >> report.md
          echo "## ROC Graph" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          echo "" >> report.md
          echo "![](./ROC.png)" >> report.md
          
          cml comment create report.md
