name: mlops-two-testing-pipeline
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install DVC and dependencies
        run: |
          pip install scikit-learn pandas numpy matplotlib seaborn
          pip install dvc gdown
      
      - name: 'Train and evaluate model'
        run: |
          # Run your DVC pipeline
          dvc repro
          
          # Format metrics in a more readable way
          echo "## Model Metrics" > report.md
          echo "" >> report.md
          echo "| Metric | Value |" >> report.md
          echo "| ------ | ----- |" >> report.md
          
          # Extract and format metrics from JSON
          python -c "
import json
with open('metrics.json', 'r') as f:
    metrics = json.load(f)
for key, value in metrics.items():
    print(f'| {key} | {value:.4f} |')
          " >> report.md
          
          echo "" >> report.md
          echo "## ROC Graph for the model" >> report.md
          
          # Save a base64 encoded version of the image
          echo "" >> report.md
          echo '<img src="https://github.com/'$GITHUB_REPOSITORY'/raw/'$GITHUB_SHA'/ROC.png" width="600">' >> report.md
      
      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            ROC.png
            metrics.json
            report.md
      
      # Use commit comment action with PAT
      - name: Create commit comment
        uses: peter-evans/commit-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          body-path: report.md
